name: flask_ml_server
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - numpy
  - scipy
  - dask
  - matplotlib
  - pandas
  - pandas-datareader
  - pytables
  - scikit-learn
  - scikit-image
  - pip
  - dask-ml
  - flask
